from __future__ import annotations

import logging,os
from datetime import datetime, timezone
from app.celery_app import celery_app

from flask import request

# For post-validation flow
from app.config.settings import settings
from app.services.ihg_servicenow_ticket_service import create_ticket_service_now
from app.services.cleanup_service import cleanup_all_outputs
from app.api.sharepoint_processor import sharepoint_download, sharepoint_upload
from app.agents.cleaning_agent import cleaning_data_prosessing
from app.services.excel_filter_service import remove_red_rows_from_excel
from app.api.sharepoint_processor import sharepoint_upload_post_validation_records, sharepoint_download_history_data
from app.api.mail_processor import post_validation_send_email, send_text_email
from app.agents.mail_reader_agent import MailReaderAgent
from app.agents.SmartFeedbackAgent import SmartFeedbackAgent

logger = logging.getLogger(__name__)

mail_agent = MailReaderAgent()

#===============Log handaling========================
logger.setLevel(logging.INFO)

# Create file handler
file_handler = logging.FileHandler("C:\\temp\\celery_task_debug.log")
file_handler.setLevel(logging.INFO)

# Formatter
formatter = logging.Formatter(
    "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
file_handler.setFormatter(formatter)

# Attach handler (avoid duplicate handlers)
if not logger.handlers:
    logger.addHandler(file_handler)

# Celery task to run the clean data flow
@celery_app.task(name="app.tasks.run_clean_data_flow")
def run_clean_data_flow_task():
    """Run the SharePoint download, cleaning, upload, and ServiceNow Agent asynchronously."""
    try:
        base_remote_path = "/Monthly Billing Clean Data/".rstrip("/")  # Ensure no trailing slash
        local_dir = settings.output_dir
        
        logger.info("Step 1: Files download from SharePoint Agent started.....................")
        attempt = 1
        download_result = sharepoint_download('Cleaning_Agent')
        if attempt < 2 and download_result.get("status") != "Monthly report files downloaded. History CROP files downloaded. History NON-CROP files downloaded. ":
            attempt += 1
            download_result = sharepoint_download('Cleaning_Agent') # retry once if there was an error, as SharePoint can be flaky. If it fails again, we will log the error and continue with the flow, as the cleaning process can still be useful for any files that were downloaded successfully.
        logger.info("Step 1: Files download from SharePoint Agent completed: %s", download_result)

        logger.info("Step 2: Cleaning Agent started..............................")
        cleaning_data_prosessing()
        logger.info("Step 2: Cleaning Agent completed........................................")

        
        logger.info("Step 3: File upload on SharePoint Agent started............................")
        month_folder = datetime.now().strftime("%B_%Y")
        remote_path = f"{base_remote_path}/{month_folder}"
        local_dir = local_dir+"/Monthly_cleaned_report"
        upload_result = sharepoint_upload(remote_path, local_dir)
        logger.info("Step 3: File upload on SharePoint Agent completed: %s", upload_result)

        payload = {
            "requested_by": "AMER\\USM3PA",
            "requested_for": "AMER\\USM3PA",
            "location": "ATLR3",
            "situation": "other",
            "business_service": "IHG University",
            "service_category": "Application Support",
            "assignment_group": "IY-GLBL-LMS Support Accenture",
            "short_description": "LMS Monthly Billing Process - MyID Data Retrieve",
            "description": """This ticket is generated by the Billing Agent to initiate the automated bot, 
which retrieves missing cost center and Holidex codes from the MyID system.

Note: Please do not make any changes to the ticket, as it will be automatically processed and closed by the agent.""",
            "internal_notes": "",
            "source": "RCC Tech Intake Form",
        }

        logger.info("Step 4: ServiceNow ticket creation Agent started.......................................")
        response = create_ticket_service_now(payload)
        logger.info("Step 4: ServiceNow ticket creation Agent completed: %s", response)

        logger.info("File download, cleaning data, File upload, and ServiceNow Agent completed successfully")
        return True 

    except Exception as exc:
        logger.exception("Background flow failed: %s", exc)
             


# Celery task to run post-validation flow in strict order
@celery_app.task(name="app.tasks.run_post_validation_flow_task")
def run_post_validation_flow_task():
    """
    Celery task: Run post-validation flow in strict order.
    Steps:
      1. remove_red_rows_from_excel
      2. sharepoint_upload_post_validation_records
      3. create_ticket_service_now
      4. post_validation_send_email
    Returns a summary dict or error.
    """

    try:
        # Step 1: Mail reader agent to fetch emails and save attachments
        # limit = request.args.get("limit", 25, type=int)
        logger.info("Step 1: MailBox reader Agent started.......................................")
        limit = 1
        attachment_dir = "data/Post_Validation_Data"
        subject = "RE: Monthly Billing Records ({}) - Corp and Non-Corp Records for Validation".format(datetime.now().strftime("%B %Y"))
        emails = mail_agent.fetch_unread(limit=limit, attachment_dir=attachment_dir, subject=subject)
        logger.info("Step 1: Fetched %d emails from mail, reader Agent  completed", len(emails))
        if len(emails)<1:
            logger.info("No unread emails found. Skipping mail reader AI Agent execution.")
            return {"status": "No emails to process"}
        # Mark each email as read after processing
        for email in emails:
            try:
                mail_agent._client.mark_as_read(email.id)
            except Exception as exc:
                logger.warning(f"Failed to mark email {getattr(email, 'id', None)} as read: {exc}")
    except Exception as exc:
        logger.warning("Failed mail reader Agent to fetch emails : %s", exc)
        return {"error": str(exc)}
    
    folder_path = "data/Post_Validation_Data"
    if not os.path.exists(folder_path) or not os.listdir(folder_path):
        logger.warning(f"No files found in {folder_path} by mail reader Agent.")
        return {"error": f"No files found in {folder_path} for processing."}
    
    safe_name = os.listdir(settings.upload_dir+"/Post_validation_data/")[0]
    ext = os.path.splitext(safe_name)[1].lower()
    if ext not in {".xlsx", ".xlsm", ".xltx", ".xltm"}:
        return {"error": "Only Excel files are supported (.xlsx, .xlsm, .xltx, .xltm)."}


    # Step 2:Send file recived email
    logger.info("Step 2: SendMail agent triggered successfully. File receipt confirmed. ............................")
    send_text_email()

    try:
        # Step 3: Download Manual entry file from sharepoint
        logger.info("Step 3: Files download from SharePoint Agent started.....................")
        download_result = sharepoint_download('Post_validation_Agent')
        logger.info("Step 3: Files download from SharePoint Agent completed: %s", download_result)
    except Exception as exc:
        logger.error("Step 3: Files download from SharePoint Agent failed: %s", exc)
        # Do not stop the flow if file not found or error occurs, just log and continue
        pass

    # Step 4: Remove red-highlighted rows
    filename = os.listdir(settings.upload_dir+"/Post_validation_data/")[0]
    source_path = os.path.join(settings.upload_dir, "Post_validation_data", filename)
    output_dir = settings.upload_dir
    try:
        logger.info("Step 4: Clasification Agent remove_red_rows_from_excel started...........")
        cleaned_path = remove_red_rows_from_excel(
            input_file_path=source_path,
            output_dir=output_dir,
        )
        logger.info("Step 4: Clasification Agent remove_red_rows_from_excel completed: %s", cleaned_path)
    except Exception as exc:
        logger.error("Step 4 failed: %s", exc)
        return {"error": f" Step 4: Clasification Agent failed to remove_red_rows_from_excel: {exc}"}

    # Step 5: SharePoint upload
    try:
        logger.info("Step 5: File Upload Agent started................................")
        upload_result = sharepoint_upload_post_validation_records()
        logger.info("Step 5: File Upload Agent completed: %s", upload_result)
    except Exception as exc:
        logger.error("Step 5 failed: %s", exc)
        return {"error": f" Step 5: Upload Agent failed for sharepoint upload post validation records: {exc}"}

    # Step 6: ServiceNow ticket
    payload = {
        "requested_by": "AMER\\USM3PA",
        "requested_for": "AMER\\USM3PA",
        "location": "ATLR3",
        "situation": "other",
        "business_service": "IHG University",
        "service_category": "Application Support",
        "assignment_group": "IY-GLBL-LMS Support Accenture",
        "short_description": "LMS Monthly Billing Process - PS Upload",
        "description": """"This ticket has been generated by the Billing Agent to initiate the automated bot process for uploading data to PeopleSoft.
        
Note: Please do not make any changes to this ticket, as it will be automatically processed and closed by the agent.""",
        "internal_notes": "",
        "source": "RCC Tech Intake Form"
    }
    try:
        logger.info("Step 6: Ticket initiator Agent started for PS Upload .......................")
        servicenow_result = create_ticket_service_now(payload)
        logger.info("Step 6: Ticket initiator Agent completed PS Upload : %s", servicenow_result)
    except Exception as exc:
        logger.error("Step 6: Ticket initiator Agent PS Upload failed: %s", exc)
        return {"error": f"create_ticket_service_now failed: {exc}"}

    # Step 7: Post-validation send email
    try:
        logger.info("Step 7: SendMail Agent started for Post validation............................")
        post_validation_send_email()
        logger.info("Step 7: SendMail Agent completed for Post validation ............................")
    except Exception as exc:
        logger.error("Step 7: SendMail Agent failed for Post validation: %s", exc)
        return {"error": f"post_validation_send_email failed: {exc}"}

    # Schedule cleanup task to run after 6 hours (21600 seconds)
    try:
        logger.info("Step 8: Cleanup Agent will started in 6 minutes...................................")
        run_cleanup_task.apply_async(countdown=3600)
        logger.info("Step 8: Cleanup Agent completed local files cleanup.............................")
    except Exception as exc:
        logger.error(" Step 8: Cleanup Agent Failed to cleanup local files : %s", exc)

    return {
        "status": "ok",
        "cleaned_file": cleaned_path,
        "upload_result": str(upload_result),
        "servicenow_result": str(servicenow_result),
    }

@celery_app.task(name="app.tasks.feedback_process")
def feedback_process_task():
        """Test SmartFeedbackAgent response generation with a sample email body."""
        feedback = SmartFeedbackAgent()
        
        try:
            #Step1: Fetched un read mails from the mailbox using mail agent
            logger.info("Step 1: MailBox reader Agent started.......................................")
            emails = mail_agent.fetch_unread(limit=1)
            print("Fetched Emails:", emails)
            if len(emails)<1:
                logger.info("No unread emails found. Skipping mail reader AI Agent execution.")
                return {"status": "No emails to process"}
            
            # Mark each email as read after processing
            for email in emails:
                try:
                    mail_agent._client.mark_as_read(email.id)
                except Exception as exc:
                    logger.warning(f"Failed to mark email {getattr(email, 'id', None)} as read: {exc}")
            logger.info("Step 1: MailBox reader Agent completed.......................................%s", len(emails))

            #Step2: Download files from SharePoint using sharepoint agent, as feedback agent needs to access the history files to classify the email and extract order number
            logger.info("Step 2: Files download from SharePoint Agent started.......................................")  
            download_response = sharepoint_download_history_data()
            logger.info("Step 2: Files download from SharePoint Agent completed.......................................%s", download_response)

            #Step3: Mail classification using smart feedback agent
            logger.info("Step 3: Feedback Agent order number extraction started.......................................")
            response = feedback.search_order_number(emails[0])
            if response['status'] == 'success':
                print("Extracted Order Number:", response)
                logger.info("Step 3: Feedback Agent order number extraction completed.......................................%s", response)

                #Step4: Uploading the file on sharepoint using sharepoint agent, as feedback agent needs to access the history files to classify the email and extract order number
                logger.info("Step 4: File Upload Agent started................................")    
                remote_path = f"/feedback"
                local_dir = "feedback/feedback_data"
                upload_result = sharepoint_upload(remote_path, local_dir)
                logger.info("Step 4: File Upload Agent completed: %s", upload_result)

            return {
                    "status": "success",
                    "message": "Feedback process executed successfully",
                    "response": response,
                }
        except Exception as exc:
            print("An error occurred while processing emails:", exc)
            return {
                    "status": "error",
                    "message": f"An error occurred: {str(exc)}",
                }   


@celery_app.task(name="app.tasks.run_cleanup_task")
def run_cleanup_task():
    logger.info("Starting Cleanup Agent for output folders................................................")
    cleanup_all_outputs()
    logger.info("Cleanup Agent for task completed.......................................................")
    return {"status": "cleanup completed"}



